package com.com.sky.downloader.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hellocat.bean.Breed;
import com.example.hellocat.bean.FavouriteCats;

import com.com.sky.downloader.greendao.BreedDao;
import com.com.sky.downloader.greendao.FavouriteCatsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig breedDaoConfig;
    private final DaoConfig favouriteCatsDaoConfig;

    private final BreedDao breedDao;
    private final FavouriteCatsDao favouriteCatsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        breedDaoConfig = daoConfigMap.get(BreedDao.class).clone();
        breedDaoConfig.initIdentityScope(type);

        favouriteCatsDaoConfig = daoConfigMap.get(FavouriteCatsDao.class).clone();
        favouriteCatsDaoConfig.initIdentityScope(type);

        breedDao = new BreedDao(breedDaoConfig, this);
        favouriteCatsDao = new FavouriteCatsDao(favouriteCatsDaoConfig, this);

        registerDao(Breed.class, breedDao);
        registerDao(FavouriteCats.class, favouriteCatsDao);
    }
    
    public void clear() {
        breedDaoConfig.clearIdentityScope();
        favouriteCatsDaoConfig.clearIdentityScope();
    }

    public BreedDao getBreedDao() {
        return breedDao;
    }

    public FavouriteCatsDao getFavouriteCatsDao() {
        return favouriteCatsDao;
    }

}
